<?php

/**
 * @file
 * Contains manny_dev.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_help().
 */
function manny_dev_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the manny_dev module.
    case 'help.page.manny_dev':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('my awesome module') . '</p>';
      return $output;

    default:
  }
}
